<a href="https://colab.research.google.com/github/N1a2t3a/.HW_1/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy


In [10]:
import numpy as np

vector = np.arange(1, 11)

print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
import numpy as np

matrix = np.zeros((3, 3))

print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
import numpy as np

random_array = np.random.randint(1, 11, (5, 5))

print(random_array)

[[ 3  9  8  4  7]
 [ 1  7  1 10  5]
 [ 9  5  1  8  9]
 [ 9 10  8  4  8]
 [ 8  6  7  4  9]]


In [12]:
import numpy as np

random_float_array = np.random.rand(4, 4)

print(random_float_array)

[[0.8009508  0.56935519 0.31472811 0.50616707]
 [0.55493206 0.13740074 0.28044597 0.39782142]
 [0.93484157 0.1251463  0.95528532 0.35234382]
 [0.64934931 0.74379425 0.98097738 0.78689729]]


In [13]:
import numpy as np

array1 = np.random.randint(1, 11, 5)
array2 = np.random.randint(1, 11, 5)

print("Перший масив:", array1)
print("Другий масив:", array2)

addition_result = np.add(array1, array2)
print("Результат додавання:", addition_result)

subtraction_result = np.subtract(array1, array2)
print("Результат віднімання:", subtraction_result)

multiplication_result = np.multiply(array1, array2)
print("Результат множення:", multiplication_result)

Перший масив: [ 1 10  6  5  6]
Другий масив: [3 9 6 1 7]
Результат додавання: [ 4 19 12  6 13]
Результат віднімання: [-2  1  0  4 -1]
Результат множення: [ 3 90 36  5 42]


In [15]:
import numpy as np

vector1 = np.array([1, 2, 3, 4, 5, 6, 7])
vector2 = np.array([7, 6, 5, 4, 3, 2, 1])

dot_product = np.dot(vector1, vector2)

print(dot_product)

84


In [16]:
import numpy as np

matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 3))

print(matrix1)
print(matrix2)

result_matrix = np.dot(matrix1, matrix2)

print(result_matrix)

[[ 7 10]
 [ 2  2]]
[[3 9 3]
 [8 6 6]]
[[101 123  81]
 [ 22  30  18]]


In [17]:
import numpy as np

matrix = np.random.randint(1, 11, (3, 3))
print(matrix)

try:
    inverse_matrix = np.linalg.inv(matrix)
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("\nЦя матриця є виродженою та не має оберненої матриці.")

[[1 2 9]
 [8 1 9]
 [4 8 5]]
[[-0.14408602  0.13333333  0.01935484]
 [-0.00860215 -0.06666667  0.13548387]
 [ 0.12903226  0.         -0.03225806]]


In [18]:
import numpy as np

matrix = np.random.rand(4, 4)
print(matrix)

transposed_matrix = np.transpose(matrix)
print(transposed_matrix)

[[0.57131885 0.38760007 0.20857283 0.3374379 ]
 [0.28464252 0.0817012  0.92787558 0.13903948]
 [0.09881128 0.88597922 0.88233008 0.69467104]
 [0.6873864  0.14759552 0.99514639 0.22914763]]
[[0.57131885 0.28464252 0.09881128 0.6873864 ]
 [0.38760007 0.0817012  0.88597922 0.14759552]
 [0.20857283 0.92787558 0.88233008 0.99514639]
 [0.3374379  0.13903948 0.69467104 0.22914763]]


In [19]:
import numpy as np

matrix = np.random.randint(1, 11, (3, 4))

vector = np.random.randint(1, 11, 4)

print(matrix)
print(vector)

result = np.dot(matrix, vector)

print(result)

[[7 1 5 3]
 [7 9 1 5]
 [7 3 1 8]]
[8 3 7 9]
[121 135 144]


In [20]:
import numpy as np

matrix = np.random.rand(2, 3)

vector = np.random.rand(3)

print(matrix)
print(vector)

result = np.dot(matrix, vector)

print(result)

[[0.08237784 0.16550127 0.85162542]
 [0.38207077 0.09306742 0.15834555]]
[0.14740798 0.75248051 0.03837993]
[0.16936496 0.13242899]


In [21]:
import numpy as np

matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 2))

print(matrix1)
print(matrix2)

result = np.multiply(matrix1, matrix2)

print(result)

[[9 7]
 [6 7]]
[[ 5  8]
 [ 6 10]]
[[45 56]
 [36 70]]


In [22]:
import numpy as np

matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 2))

print(matrix1)
print(matrix2)

result = np.dot(matrix1, matrix2)

print(result)

[[10  8]
 [ 9  9]]
[[8 8]
 [8 7]]
[[144 136]
 [144 135]]


In [23]:
import numpy as np

matrix = np.random.randint(1, 101, (5, 5))
print(matrix)

sum_of_elements = np.sum(matrix)
print(sum_of_elements)

[[60 33 22 82 99]
 [37 64 96 57 82]
 [25 34 12 97 50]
 [80 66 43 58 10]
 [68 51 78 76 61]]
1441


In [24]:
import numpy as np

matrix1 = np.random.randint(1, 11, (4, 4))
matrix2 = np.random.randint(1, 11, (4, 4))

print(matrix1)
print(matrix2)

result = np.subtract(matrix1, matrix2)
print(result)

[[4 7 4 7]
 [4 2 8 5]
 [8 6 4 4]
 [1 6 3 4]]
[[ 4  1  8  8]
 [ 6 10  7 10]
 [ 9  9  4  7]
 [ 3  1  8  5]]
[[ 0  6 -4 -1]
 [-2 -8  1 -5]
 [-1 -3  0 -3]
 [-2  5 -5 -1]]


In [25]:
import numpy as np

matrix = np.random.rand(3, 3)
print(matrix)

row_sums = np.sum(matrix, axis=1, keepdims=True)
print(row_sums)

[[0.59241646 0.00721078 0.49414619]
 [0.6840006  0.28818563 0.89251997]
 [0.71150275 0.98162776 0.14273881]]
[[1.09377343]
 [1.8647062 ]
 [1.83586933]]


In [26]:
import numpy as np

matrix = np.random.randint(1, 11, (3, 4))
print(matrix)

squared_matrix = np.square(matrix)
print(squared_matrix)

[[ 3  6  5 10]
 [ 9  4  8  2]
 [ 4  5  8  5]]
[[  9  36  25 100]
 [ 81  16  64   4]
 [ 16  25  64  25]]


In [27]:
import numpy as np

vector = np.random.randint(1, 51, 4)
print(vector)

sqrt_vector = np.sqrt(vector)
print(sqrt_vector)

[37 31 39 49]
[6.08276253 5.56776436 6.244998   7.        ]
